// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BlogPostHeader: typeof import('./src/components/BlogPostHeader.vue')['default']
    BlogPosts: typeof import('./src/components/BlogPosts.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonLink: typeof import('./src/components/ButtonLink.vue')['default']
    CallToAction: typeof import('./src/components/CallToAction.vue')['default']
    ContactNewBusinessButton: typeof import('./src/components/ContactNewBusinessButton.vue')['default']
    ContactOptions: typeof import('./src/components/ContactOptions.vue')['default']
    Feature: typeof import('./src/components/Feature.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    HeaderAnimation: typeof import('./src/components/HeaderAnimation.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    InlineImage: typeof import('./src/components/InlineImage.vue')['default']
    JobPostHeader: typeof import('./src/components/JobPostHeader.vue')['default']
    Locations: typeof import('./src/components/Locations.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    PageLayout2: typeof import('./src/components/PageLayout2.vue')['default']
    Prose: typeof import('./src/components/Prose.vue')['default']
    Section: typeof import('./src/components/Section.vue')['default']
    SectionHeading: typeof import('./src/components/SectionHeading.vue')['default']
    Stat: typeof import('./src/components/Stat.vue')['default']
    StatBox: typeof import('./src/components/StatBox.vue')['default']
    Stories: typeof import('./src/components/Stories.vue')['default']
    SubElement: typeof import('./src/components/SubElement.vue')['default']
    SubFeature: typeof import('./src/components/SubFeature.vue')['default']
    Team: typeof import('./src/components/Team.vue')['default']
    Vacancies: typeof import('./src/components/Vacancies.vue')['default']
    WeAreHiring: typeof import('./src/components/WeAreHiring.vue')['default']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
  }
}

export { }
