// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CallToAction: typeof import('./src/components/CallToAction.vue')['default']
    ContactOption: typeof import('./src/components/ContactOption.vue')['default']
    ContactOptions: typeof import('./src/components/ContactOptions.vue')['default']
    CustomThing: typeof import('./src/components/CustomThing.vue')['default']
    Feature: typeof import('./src/components/Feature.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HideProps: typeof import('./src/components/HideProps.vue')['default']
    Locations: typeof import('./src/components/Locations.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    Prose: typeof import('./src/components/Prose.vue')['default']
    Section: typeof import('./src/components/Section.vue')['default']
    SectionHeading: typeof import('./src/components/SectionHeading.vue')['default']
    StatBox: typeof import('./src/components/StatBox.vue')['default']
    SubElement: typeof import('./src/components/SubElement.vue')['default']
    SubFeature: typeof import('./src/components/SubFeature.vue')['default']
    Team: typeof import('./src/components/Team.vue')['default']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
  }
}

export { }
